<select id="ir01_1300_V30_searchAllotmentByRsvnPlaceMaster" resultClass="java.util.HashMap">
			SELECT
		        AAA.ROOM_TYPE_CODE
		       ,AAA.ROOM_TYPE_NAME
		       ,AAA.RSVN_PLACE_CODE
		       
		       ,AAA.RSVN_PLACE_CODE_NAME
               ,AAA.TOTL_ROOMS

			   ,AAA.UN_ALLT_ROOMS_1
		       ,AAA.ALLT_ROOMS_1
		       ,AAA.RSVN_ROOMS_1
		       ,AAA.WAIT_ROOMS_1
		       ,AAA.AVAI_ROOMS_1
		       ,AAA.CUT_OFF_YN_1

		       ,AAA.UN_ALLT_ROOMS_2
		       ,AAA.ALLT_ROOMS_2
		       ,AAA.RSVN_ROOMS_2
		       ,AAA.WAIT_ROOMS_2
		       ,AAA.AVAI_ROOMS_2
		       ,AAA.CUT_OFF_YN_2

		       ,AAA.UN_ALLT_ROOMS_3
		       ,AAA.ALLT_ROOMS_3
		       ,AAA.RSVN_ROOMS_3
		       ,AAA.WAIT_ROOMS_3
		       ,AAA.AVAI_ROOMS_3
		       ,AAA.CUT_OFF_YN_3

		       ,AAA.UN_ALLT_ROOMS_4
		       ,AAA.ALLT_ROOMS_4
		       ,AAA.RSVN_ROOMS_4
		       ,AAA.WAIT_ROOMS_4
		       ,AAA.AVAI_ROOMS_4
		       ,AAA.CUT_OFF_YN_4

		       ,AAA.UN_ALLT_ROOMS_5
		       ,AAA.ALLT_ROOMS_5
		       ,AAA.RSVN_ROOMS_5
		       ,AAA.WAIT_ROOMS_5
		       ,AAA.AVAI_ROOMS_5
		       ,AAA.CUT_OFF_YN_5

		       ,AAA.UN_ALLT_ROOMS_6
		       ,AAA.ALLT_ROOMS_6
		       ,AAA.RSVN_ROOMS_6
		       ,AAA.WAIT_ROOMS_6
		       ,AAA.AVAI_ROOMS_6
		       ,AAA.CUT_OFF_YN_6

		       ,AAA.UN_ALLT_ROOMS_7
		       ,AAA.ALLT_ROOMS_7
		       ,AAA.RSVN_ROOMS_7
		       ,AAA.WAIT_ROOMS_7
		       ,AAA.AVAI_ROOMS_7
		       ,AAA.CUT_OFF_YN_7

		       ,AAA.UN_ALLT_ROOMS_8
		       ,AAA.ALLT_ROOMS_8
		       ,AAA.RSVN_ROOMS_8
		       ,AAA.WAIT_ROOMS_8
		       ,AAA.AVAI_ROOMS_8
		       ,AAA.CUT_OFF_YN_8

		       ,AAA.UN_ALLT_ROOMS_9
		       ,AAA.ALLT_ROOMS_9
		       ,AAA.RSVN_ROOMS_9
		       ,AAA.WAIT_ROOMS_9
		       ,AAA.AVAI_ROOMS_9
		       ,AAA.CUT_OFF_YN_9

		       ,AAA.UN_ALLT_ROOMS_10
		       ,AAA.ALLT_ROOMS_10
		       ,AAA.RSVN_ROOMS_10
		       ,AAA.WAIT_ROOMS_10
		       ,AAA.AVAI_ROOMS_10
		       ,AAA.CUT_OFF_YN_10

		       ,AAA.UN_ALLT_ROOMS_11
		       ,AAA.ALLT_ROOMS_11
		       ,AAA.RSVN_ROOMS_11
		       ,AAA.WAIT_ROOMS_11
		       ,AAA.AVAI_ROOMS_11
		       ,AAA.CUT_OFF_YN_11

		       ,AAA.UN_ALLT_ROOMS_12
		       ,AAA.ALLT_ROOMS_12
		       ,AAA.RSVN_ROOMS_12
		       ,AAA.WAIT_ROOMS_12
		       ,AAA.AVAI_ROOMS_12
		       ,AAA.CUT_OFF_YN_12

		       ,AAA.UN_ALLT_ROOMS_13
		       ,AAA.ALLT_ROOMS_13
		       ,AAA.RSVN_ROOMS_13
		       ,AAA.WAIT_ROOMS_13
		       ,AAA.AVAI_ROOMS_13
		       ,AAA.CUT_OFF_YN_13

		       ,AAA.UN_ALLT_ROOMS_14
		       ,AAA.ALLT_ROOMS_14
		       ,AAA.RSVN_ROOMS_14
		       ,AAA.WAIT_ROOMS_14
		       ,AAA.AVAI_ROOMS_14
		       ,AAA.CUT_OFF_YN_14

		       ,AAA.UN_ALLT_ROOMS_15
		       ,AAA.ALLT_ROOMS_15
		       ,AAA.RSVN_ROOMS_15
		       ,AAA.WAIT_ROOMS_15
		       ,AAA.AVAI_ROOMS_15
		       ,AAA.CUT_OFF_YN_15

		       ,AAA.UN_ALLT_ROOMS_16
		       ,AAA.ALLT_ROOMS_16
		       ,AAA.RSVN_ROOMS_16
		       ,AAA.WAIT_ROOMS_16
		       ,AAA.AVAI_ROOMS_16
		       ,AAA.CUT_OFF_YN_16

		       ,AAA.UN_ALLT_ROOMS_17
		       ,AAA.ALLT_ROOMS_17
		       ,AAA.RSVN_ROOMS_17
		       ,AAA.WAIT_ROOMS_17
		       ,AAA.AVAI_ROOMS_17
		       ,AAA.CUT_OFF_YN_17

		       ,AAA.UN_ALLT_ROOMS_18
		       ,AAA.ALLT_ROOMS_18
		       ,AAA.RSVN_ROOMS_18
		       ,AAA.WAIT_ROOMS_18
		       ,AAA.AVAI_ROOMS_18
		       ,AAA.CUT_OFF_YN_18

		       ,AAA.UN_ALLT_ROOMS_19
		       ,AAA.ALLT_ROOMS_19
		       ,AAA.RSVN_ROOMS_19
		       ,AAA.WAIT_ROOMS_19
		       ,AAA.AVAI_ROOMS_19
		       ,AAA.CUT_OFF_YN_19

		       ,AAA.UN_ALLT_ROOMS_20
		       ,AAA.ALLT_ROOMS_20
		       ,AAA.RSVN_ROOMS_20
		       ,AAA.WAIT_ROOMS_20
		       ,AAA.AVAI_ROOMS_20
		       ,AAA.CUT_OFF_YN_20

		       ,AAA.UN_ALLT_ROOMS_21
		       ,AAA.ALLT_ROOMS_21
		       ,AAA.RSVN_ROOMS_21
		       ,AAA.WAIT_ROOMS_21
		       ,AAA.AVAI_ROOMS_21
		       ,AAA.CUT_OFF_YN_21
			FROM(
			SELECT  
			    M.ROOM_TYPE_CODE
		       ,M.ROOM_TYPE_NAME		       
		       ,M.RSVN_PLACE_CODE
		       ,M.RSVN_PLACE_CODE_NAME
		       ,M.BSNS_CODE
               ,M.PROPERTY_NO
               ,M.ROOM_CNT                                AS TOTL_ROOMS
		       ,M.RSVN_PLACE_CODE||M.ROOM_TYPE_CODE       AS CONNECT_RSVN
		       
		       ,SUM(CASE WHEN M.SALE_DATE = #START_DATE# THEN M.NOT_ALLOT_CNT ELSE NULL END)                                                              			AS UN_ALLT_ROOMS_1 
		       ,SUM(CASE WHEN M.SALE_DATE = #START_DATE# THEN M.ALLOTMENT ELSE NULL END)                                                                            AS ALLT_ROOMS_1 
		       ,SUM(CASE WHEN M.SALE_DATE = #START_DATE# THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                                                                     AS RSVN_ROOMS_1
		       ,SUM(CASE WHEN M.SALE_DATE = #START_DATE# THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                                                                     AS WAIT_ROOMS_1
		       ,SUM(CASE WHEN M.SALE_DATE = #START_DATE# THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = #START_DATE# THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = #START_DATE# THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 																	AS AVAI_ROOMS_1
			   ,MAX(CASE WHEN M.SALE_DATE = #START_DATE# THEN M.CUT_OFF_YN ELSE 'N' END) 																			AS CUT_OFF_YN_1
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+1, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                   			AS UN_ALLT_ROOMS_2
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+1, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                                AS ALLT_ROOMS_2
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+1, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                         AS RSVN_ROOMS_2
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+1, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                         AS WAIT_ROOMS_2
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+1, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+1, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+1, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_2
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+1, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_2
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+2, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                   			AS UN_ALLT_ROOMS_3
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+2, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                                AS ALLT_ROOMS_3
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+2, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                         AS RSVN_ROOMS_3
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+2, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                         AS WAIT_ROOMS_3
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+2, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+2, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+2, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_3
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+2, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END)	 							AS CUT_OFF_YN_3
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+3, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)               				AS UN_ALLT_ROOMS_4
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+3, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                                AS ALLT_ROOMS_4
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+3, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                         AS RSVN_ROOMS_4
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+3, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                         AS WAIT_ROOMS_4
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+3, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+3, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+3, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_4
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+3, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_4
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+4, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                   			AS UN_ALLT_ROOMS_5
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+4, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                                AS ALLT_ROOMS_5
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+4, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                         AS RSVN_ROOMS_5
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+4, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                         AS WAIT_ROOMS_5
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+4, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+4, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+4, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_5
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+4, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_5
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+5, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                 			AS UN_ALLT_ROOMS_6
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+5, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                                AS ALLT_ROOMS_6
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+5, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                         AS RSVN_ROOMS_6
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+5, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                         AS WAIT_ROOMS_6
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+5, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+5, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+5, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_6
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+5, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_6
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+6, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_7
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+6, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                                AS ALLT_ROOMS_7
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+6, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                         AS RSVN_ROOMS_7
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+6, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                         AS WAIT_ROOMS_7
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+6, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+6, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+6, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_7
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+6, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END)								AS CUT_OFF_YN_7
			   
			   ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+7, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)              				AS UN_ALLT_ROOMS_8
			   ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+7, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                                AS ALLT_ROOMS_8
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+7, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                         AS RSVN_ROOMS_8
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+7, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                         AS WAIT_ROOMS_8
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+7, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+7, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+7, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_8
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+7, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_8
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+8, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                   			AS UN_ALLT_ROOMS_9
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+8, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                                AS ALLT_ROOMS_9
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+8, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                         AS RSVN_ROOMS_9
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+8, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                         AS WAIT_ROOMS_9
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+8, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+8, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+8, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_9
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+8, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END)	 							AS CUT_OFF_YN_9
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+9, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                   			AS UN_ALLT_ROOMS_10
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+9, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                                AS ALLT_ROOMS_10
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+9, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                         AS RSVN_ROOMS_10
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+9, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                         AS WAIT_ROOMS_10
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+9, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+9, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+9, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_10
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+9, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_10
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+10, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_11
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+10, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_11
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+10, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_11
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+10, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_11
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+10, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+10, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+10, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_11
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+10, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_11
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+11, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_12
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+11, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_12
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+11, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_12
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+11, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_12
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+11, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+11, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+11, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_12
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+11, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_12
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+12, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_13
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+12, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_13
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+12, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_13
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+12, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_13
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+12, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+12, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+12, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_13
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+12, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END)								AS CUT_OFF_YN_13
			   
			   ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+13, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                 			AS UN_ALLT_ROOMS_14
			   ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+13, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_14
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+13, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_14
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+13, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_14
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+13, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+13, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+13, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_14
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+13, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_14
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+14, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_15
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+14, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_15
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+14, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_15
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+14, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_15
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+14, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+14, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+14, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_15
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+14, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END)	 							AS CUT_OFF_YN_15
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+15, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_16
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+15, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_16
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+15, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_16
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+15, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_16
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+15, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+15, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+15, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_16
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+15, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_16
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+16, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_17
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+16, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_17
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+16, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_17
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+16, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_17
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+16, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+16, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+16, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_17
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+16, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_17
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+17, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_18
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+17, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_18
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+17, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_18
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+17, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_18
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+17, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+17, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+17, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_18
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+17, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_18
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+18, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                 		 	AS UN_ALLT_ROOMS_19
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+18, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_19
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+18, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_19
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+18, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_19
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+18, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+18, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+18, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_19
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+18, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END)								AS CUT_OFF_YN_19
			   
			   ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+19, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_20
			   ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+19, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_20
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+19, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_20
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+19, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_20
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+19, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+19, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+19, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_20
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+19, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END) 								AS CUT_OFF_YN_20
			   
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+20, 'YYYYMMDD') THEN M.NOT_ALLOT_CNT ELSE NULL END)                  			AS UN_ALLT_ROOMS_21
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+20, 'YYYYMMDD') THEN M.ALLOTMENT ELSE NULL END)                               AS ALLT_ROOMS_21
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+20, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END)                        AS RSVN_ROOMS_21
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+20, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END)                        AS WAIT_ROOMS_21
		       ,SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+20, 'YYYYMMDD') THEN M.ALLOTMENT ELSE 0 END)
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+20, 'YYYYMMDD') THEN NVL(M.RSVN_ROOMS , 0) ELSE 0 END) 
		       -SUM(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+20, 'YYYYMMDD') THEN NVL(M.WAIT_ROOMS , 0) ELSE 0 END) 						AS AVAI_ROOMS_21
			   ,MAX(CASE WHEN M.SALE_DATE = TO_CHAR(TO_DATE(#START_DATE#, 'YYYYMMDD')+20, 'YYYYMMDD') THEN M.CUT_OFF_YN ELSE 'N' END)	 							AS CUT_OFF_YN_21
		  FROM (

                SELECT T1.BSNS_CODE
				      ,T1.PROPERTY_NO
				      ,T2.SALE_DATE
				      ,T1.ROOM_TYPE_CODE
				      ,T1.ROOM_TYPE_CODE || ' [ ' || T1.ROOM_CNT || ' ] ' AS ROOM_TYPE_NAME
				      ,T9.RSVN_PLACE_CODE
				      ,FN_ZZ_MULTI_NAME_OTH(T9.RSVN_PLACE_CODE_NAME,T9.RSVN_PLACE_CODE_ENG_NAME,T9.RSVN_PLACE_CODE_OTH_NAME,#SS_LANG_TYPE#) AS RSVN_PLACE_CODE_NAME
				      ,T1.ROOM_CNT                                                   AS ROOM_CNT
				      ,NVL(T4.OOO_ROOM_CNT,0)                                        AS OOO_ROOM_CNT
				      ,NVL(T3.ALLOTMENT,0)                                          AS ALLOTMENT
				      ,T1.ROOM_CNT - (NVL(T10.ALLOTMENT,0) + NVL(T4.OOO_ROOM_CNT,0)) AS NOT_ALLOT_CNT
				      ,NVL(SUM(T5.USE_ROOM_CNT),0)                                   AS USE_ROOMS
				      ,NVL(SUM(T5.RSVN_ROOM_CNT),0) + NVL(SUM(T5.LODG_ROOM_CNT),0)   AS RSVN_ROOMS
				      ,NVL(SUM(T5.WAIT_ROOM_CNT),0)                                  AS WAIT_ROOMS
				      ,NVL(SUM(T5.LODG_ROOM_CNT),0)                                  AS LODG_ROOMS
				      ,NVL(SUM(T3.ALLOTMENT),0) - NVL(SUM(T5.USE_ROOM_CNT),0)        AS BLC_ROOMS
				      ,NVL(MAX(T3.CUT_OFF_YN),'N')                                   AS CUT_OFF_YN
				      ,T1.SORT_ORDER				      
		      
				      
				      
				  FROM (
				        SELECT A.BSNS_CODE
				              ,A.PROPERTY_NO
				              ,A.ROOM_TYPE_CODE
				              ,FN_ZZ_MULTI_NAME_OTH(A.ROOM_TYPE_NAME,A.ROOM_TYPE_ENG_NAME,A.ROOM_TYPE_OTH_NAME,#SS_LANG_TYPE#) AS ROOM_TYPE_NAME
				              ,A.ROOM_CNT
				              ,A.SORT_ORDER
				          FROM VW_FO_ROOM_TYPE A
				         WHERE BSNS_CODE           = #BSNS_CODE#
				           AND PROPERTY_NO         = #PROPERTY_NO#
				           AND ASSN_ROOM_TYPE_CODE = 'M'
				           AND USE_YN              = 'Y'
				            <isNotEmpty property="ROOM_TYPE_CODE"> 
				                AND A.ROOM_TYPE_CODE = #ROOM_TYPE_CODE# 
				            </isNotEmpty>                          
				        )T1
				      INNER JOIN TB_FO_RSVN_PLACE_CODE T9
				         ON T1.BSNS_CODE       = T9.BSNS_CODE
				        AND T1.PROPERTY_NO     = T9.PROPERTY_NO
				        AND T9.BSNS_CODE       = #BSNS_CODE#
				        AND T9.PROPERTY_NO     = #PROPERTY_NO#
				        AND T9.RSVN_PLACE_CODE = #RSVN_PLACE_CODE#
				        AND T9.USE_YN          = 'Y'							        
				 CROSS JOIN (
				             SELECT TO_CHAR(TO_DATE( #START_DATE#,'YYYYMMDD') + LEVEL - 1,'YYYYMMDD') SALE_DATE
				               FROM DUAL
				            CONNECT BY LEVEL  <![CDATA[ <= ]]> (TO_DATE( #START_DATE#,'YYYYMMDD') - TO_DATE(#START_DATE#,'YYYYMMDD')+21)
				             ) T2
				             
				 LEFT OUTER JOIN (
				                  SELECT A.BSNS_CODE
				                        ,A.PROPERTY_NO
				                        ,A.RSVN_PLACE_CODE 
				                        ,A.SALE_DATE
				                        ,A.ROOM_TYPE_CODE
				                        ,A.ALLOTMENT 
				                        ,NVL(CUT_OFF_YN,'N') AS CUT_OFF_YN
				                    FROM TB_FO_ALLT_RSVN_PLACE A
				                   WHERE A.BSNS_CODE       = #BSNS_CODE#
				                     AND A.PROPERTY_NO     = #PROPERTY_NO#
				                     AND A.RSVN_PLACE_CODE = #RSVN_PLACE_CODE# 
					            <isNotEmpty property="ROOM_TYPE_CODE"> 
					                AND A.ROOM_TYPE_CODE = #ROOM_TYPE_CODE# 
					            </isNotEmpty>    
				                 ) T3
				         ON T1.BSNS_CODE       = T3.BSNS_CODE
				        AND T1.PROPERTY_NO     = T3.PROPERTY_NO
				        AND T1.ROOM_TYPE_CODE  = T3.ROOM_TYPE_CODE
                        AND T3.RSVN_PLACE_CODE = T9.RSVN_PLACE_CODE				        
				        AND T2.SALE_DATE       = T3.SALE_DATE
				        AND T3.ALLOTMENT        <![CDATA[ <> ]]> 0	  
				 LEFT OUTER JOIN (
				                  SELECT A.BSNS_CODE
				                        ,A.PROPERTY_NO
				                        ,A.SALE_DATE
				                        ,A.ROOM_TYPE_CODE
				                        ,SUM(A.ALLOTMENT) AS ALLOTMENT 
				                    FROM TB_FO_ALLT_RSVN_PLACE A
				                   WHERE A.BSNS_CODE       = #BSNS_CODE#
				                     AND A.PROPERTY_NO     = #PROPERTY_NO#
					            <isNotEmpty property="ROOM_TYPE_CODE"> 
					                AND A.ROOM_TYPE_CODE = #ROOM_TYPE_CODE# 
					            </isNotEmpty>   
					              GROUP BY A.BSNS_CODE
				                          ,A.PROPERTY_NO
				                          ,A.SALE_DATE
				                          ,A.ROOM_TYPE_CODE
					             ) T10
				         ON T1.BSNS_CODE       = T10.BSNS_CODE
				        AND T1.PROPERTY_NO     = T10.PROPERTY_NO
				        AND T1.ROOM_TYPE_CODE  = T10.ROOM_TYPE_CODE
                        AND T2.SALE_DATE       = T10.SALE_DATE
				        AND T10.ALLOTMENT     <![CDATA[ <> ]]> 0
				        	  
				 LEFT OUTER JOIN (
				                  SELECT BSNS_CODE
				                        ,PROPERTY_NO
				                        ,SALE_DATE
				                        ,ROOM_TYPE_CODE
				                        ,SUM(OOO_ROOM_CNT) AS OOO_ROOM_CNT
				                    FROM (
				                          SELECT A.BSNS_CODE
				                                ,A.PROPERTY_NO
				                                ,B.ROOM_TYPE_CODE
				                                ,C.SALE_DATE
								                ,CASE WHEN (DENSE_RANK() OVER (PARTITION BY A.BSNS_CODE, A.PROPERTY_NO, A.ROOM_NO, C.SALE_DATE ORDER BY C.SALE_DATE, A.SEQ_NO)) = 1 THEN 1
								                      ELSE 0
								                      END OOO_ROOM_CNT
								            FROM TB_HK_OOO A
								           INNER JOIN TB_FO_RMMST B
								              ON A.BSNS_CODE           = B.BSNS_CODE
								             AND A.PROPERTY_NO         = B.PROPERTY_NO
								             AND A.ROOM_NO             = B.ROOM_NO
								             AND A.OOO_ROOM_REG_YN     = 'Y'
								             AND A.DEL_YN              = 'N'
								             AND B.SELL_ROOM_YN        = 'Y'
				                             AND B.ASSN_ROOM_TYPE_CODE  <![CDATA[ <> ]]> 'J'  
				                           CROSS JOIN (
				                                       SELECT TO_CHAR(TO_DATE( #START_DATE#, 'YYYYMMDD') + LEVEL - 1,'YYYYMMDD') SALE_DATE
				                                         FROM DUAL
				                                      CONNECT BY LEVEL  <![CDATA[ <= ]]> (TO_DATE( #START_DATE#, 'YYYYMMDD') - TO_DATE(#START_DATE#,'YYYYMMDD')+21)
				                                      ) C
				              			   WHERE A.BSNS_CODE       = #BSNS_CODE#
				                             AND A.PROPERTY_NO     = #PROPERTY_NO#
				                             AND A.DEFECT_START_DATE  <![CDATA[ <= ]]> C.SALE_DATE
				                             AND A.DEFECT_END_DATE    <![CDATA[ >= ]]> C.SALE_DATE  
				                             AND A.ROOM_DEFECT_PROC_STATUS_CODE  <![CDATA[ <> ]]> '3'
				                                
			                                <isNotEmpty property="ROOM_TYPE_CODE"> 
			                                    AND B.ROOM_TYPE_CODE = #ROOM_TYPE_CODE# 
			                                </isNotEmpty>
				                                
				                         )
				                    GROUP BY BSNS_CODE, PROPERTY_NO, SALE_DATE, ROOM_TYPE_CODE
				                 ) T4
				         ON T1.BSNS_CODE       = T4.BSNS_CODE
				        AND T1.PROPERTY_NO     = T4.PROPERTY_NO
				        AND T1.ROOM_TYPE_CODE  = T4.ROOM_TYPE_CODE
				        AND T2.SALE_DATE       = T4.SALE_DATE
				        
				 LEFT OUTER JOIN (
				                  SELECT BSNS_CODE
				                        ,PROPERTY_NO
				                
				                        ,ROOM_TYPE_CODE
				                        ,LODG_DATE          AS SALE_DATE
				                        ,SUM(RSVN_ROOM_CNT) + SUM(WAIT_ROOM_CNT) + SUM(LODG_ROOM_CNT) AS USE_ROOM_CNT
							            ,SUM(RSVN_ROOM_CNT) AS RSVN_ROOM_CNT
							            ,SUM(WAIT_ROOM_CNT) AS WAIT_ROOM_CNT
				                        ,SUM(LODG_ROOM_CNT) AS LODG_ROOM_CNT
				
												  FROM (
																  
																	SELECT  /*+ LEADING (C B) USE_NL(B A C D) */
																	       A.BSNS_CODE
																	      ,A.PROPERTY_NO
																	      ,B.RSVN_PLACE_CODE
																	      ,B.ROOM_TYPE_CODE
																	      ,C.LODG_DATE
																	      ,B.RSVN_ROOM_CNT-B.LODG_ROOM_CNT AS RSVN_ROOM_CNT
																	      ,0 AS WAIT_ROOM_CNT
																	      ,0 AS LODG_ROOM_CNT
																	  FROM TB_IR_RSVN_MST A
																	 INNER JOIN TB_IR_RSVN_DTL B
																	    ON A.RSVN_NO             = B.RSVN_NO
																	   AND A.RSVN_STATUS_CODE    = 'RR'
																	   AND B.RSVN_STATUS_CODE    = 'RR'
																	 INNER JOIN TB_IR_ROOM_RATE C
																	    ON B.RSVN_NO             = C.RSVN_NO
																	   AND B.RSVN_SEQ_NO         = C.RSVN_SEQ_NO
																	   AND C.RSVN_STATUS_CODE    = 'RR'
																	 INNER JOIN VW_FO_CFG_RMCNT_INCL_RS_STEP D
																	    ON A.BSNS_CODE           = D.BSNS_CODE
																	   AND A.PROPERTY_NO         = D.PROPERTY_NO
																	   AND A.RSVN_STEP_CODE      = D.RSVN_STEP_CODE
																	   AND NOT (A.IND_GROUP_CODE = 'F' AND A.GROUP_ID IS NOT NULL)
																	   AND NOT EXISTS( 
																	                  SELECT 'X'
																	                    FROM TB_IR_ROOM_ASSIGN X
																	                   INNER JOIN TB_FO_RMMST Y
																	                      ON X.BSNS_CODE      = Y.BSNS_CODE
																	                     AND X.PROPERTY_NO    = Y.PROPERTY_NO
																	                     AND X.ROOM_TYPE_CODE = Y.ROOM_TYPE_CODE
																	                     AND X.ROOM_NO        = Y.ROOM_NO
																	                   WHERE C.RSVN_NO        = X.RSVN_NO
																	                     AND C.RSVN_SEQ_NO    = X.RSVN_SEQ_NO
																	                     AND C.ROOM_TYPE_CODE = X.ROOM_TYPE_CODE													                                     																	                   
																	                     AND Y.ASSN_ROOM_TYPE_CODE = 'J'
																	                 )
				                                                 	 WHERE A.BSNS_CODE       = #BSNS_CODE#
				                                                       AND A.PROPERTY_NO     = #PROPERTY_NO#    
				                                                       AND B.RSVN_PLACE_CODE = #RSVN_PLACE_CODE#
				                                                        <isNotEmpty property="ROOM_TYPE_CODE"> 
				                                                            AND B.ROOM_TYPE_CODE = #ROOM_TYPE_CODE# 
				                                                        </isNotEmpty>
				
																	 UNION ALL
																  
																	SELECT  /*+ LEADING (C B) USE_NL(B A C D) */
																	       A.BSNS_CODE
																	      ,A.PROPERTY_NO
																	      ,B.RSVN_PLACE_CODE
																	      ,B.ROOM_TYPE_CODE
																	      ,C.LODG_DATE
																	      ,0 AS RSVN_ROOM_CNT
																	      ,B.RSVN_ROOM_CNT-B.LODG_ROOM_CNT AS WAIT_ROOM_CNT
																	      ,0 AS LODG_ROOM_CNT
																	  FROM TB_IR_RSVN_MST A
																	 INNER JOIN TB_IR_RSVN_DTL B
																	    ON A.RSVN_NO             = B.RSVN_NO
																	   AND A.RSVN_STATUS_CODE    = 'RW'
																	   AND B.RSVN_STATUS_CODE    = 'RW'
																	 INNER JOIN TB_IR_ROOM_RATE C
																	    ON B.RSVN_NO             = C.RSVN_NO
																	   AND B.RSVN_SEQ_NO         = C.RSVN_SEQ_NO
																	   AND C.RSVN_STATUS_CODE    = 'RW'
																	   AND NOT (A.IND_GROUP_CODE = 'F' AND A.GROUP_ID IS NOT NULL)
																	   AND NOT EXISTS( 
																	                  SELECT 'X'
																	                    FROM TB_IR_ROOM_ASSIGN X
																	                   INNER JOIN TB_FO_RMMST Y
																	                      ON X.BSNS_CODE      = Y.BSNS_CODE
																	                     AND X.PROPERTY_NO    = Y.PROPERTY_NO
																	                     AND X.ROOM_TYPE_CODE = Y.ROOM_TYPE_CODE
																	                     AND C.ROOM_TYPE_CODE = X.ROOM_TYPE_CODE	
																	                   WHERE C.RSVN_NO        = X.RSVN_NO
																	                     AND C.RSVN_SEQ_NO    = X.RSVN_SEQ_NO
																	                     AND C.ROOM_TYPE_CODE = X.ROOM_TYPE_CODE
																	                     AND Y.ASSN_ROOM_TYPE_CODE = 'J'
																	                 )
				                                                 	 WHERE A.BSNS_CODE       = #BSNS_CODE#
				                                                       AND A.PROPERTY_NO     = #PROPERTY_NO#  
                                                                       AND B.RSVN_PLACE_CODE = #RSVN_PLACE_CODE# 
				                                                        <isNotEmpty property="ROOM_TYPE_CODE"> 
				                                                            AND B.ROOM_TYPE_CODE = #ROOM_TYPE_CODE# 
				                                                        </isNotEmpty>
				                                                        
				                           							UNION ALL
																   
																	SELECT  /*+ LEADING (A B) USE_NL(B) */
																	       A.BSNS_CODE
																	      ,A.PROPERTY_NO
																	      ,A.RSVN_PLACE_CODE
																	      ,B.ROOM_TYPE_CODE
																	      ,B.LODG_DATE
																	      ,0 AS RSVN_ROOM_CNT
																	      ,0 AS WAIT_ROOM_CNT
																	      ,CASE WHEN (DENSE_RANK() OVER (PARTITION BY A.BSNS_CODE, A.PROPERTY_NO, A.ROOM_NO ORDER BY A.DEPT_DATE DESC, A.FOLIO_NO )) = 1 THEN 1 ELSE 0 END AS LODG_ROOM_CNT
																	  FROM TB_FD_REGIST A
																	 INNER JOIN TB_FD_ROOM_RATE B
																	    ON A.FOLIO_NO         = B.FOLIO_NO
																	   AND A.RSVN_STATUS_CODE = 'CI'
																	   AND B.RSVN_STATUS_CODE = 'CI'
																	   AND A.IND_GROUP_CODE   = 'F'
																	   AND NOT EXISTS( 
																	                  SELECT 'X'
																	                    FROM TB_FO_RMMST X
																	                   WHERE A.BSNS_CODE           = X.BSNS_CODE
																	                     AND A.PROPERTY_NO         = X.PROPERTY_NO 
																	                     AND A.ROOM_NO             = X.ROOM_NO
																	                     AND B.ROOM_TYPE_CODE      = X.ROOM_TYPE_CODE
																	                     AND X.ASSN_ROOM_TYPE_CODE = 'J'
																	                 )
				                                                 	 WHERE A.BSNS_CODE       = #BSNS_CODE#
				                                                       AND A.PROPERTY_NO     = #PROPERTY_NO#  
				                                                       AND A.RSVN_PLACE_CODE = #RSVN_PLACE_CODE#   
				                                                     
				                                                        <isNotEmpty property="ROOM_TYPE_CODE"> 
				                                                            AND B.ROOM_TYPE_CODE = #ROOM_TYPE_CODE# 
				                                                        </isNotEmpty>
				                       )
				                  GROUP BY BSNS_CODE, PROPERTY_NO, ROOM_TYPE_CODE, LODG_DATE 
				                 ) T5
				         ON T1.BSNS_CODE       = T5.BSNS_CODE
				        AND T1.PROPERTY_NO     = T5.PROPERTY_NO
				        AND T1.ROOM_TYPE_CODE  = T5.ROOM_TYPE_CODE
				        AND T2.SALE_DATE       = T5.SALE_DATE
				GROUP BY
					T1.BSNS_CODE,
					T1.PROPERTY_NO,
					T2.SALE_DATE,
					T1.ROOM_TYPE_CODE,
					T9.RSVN_PLACE_CODE,
					T9.RSVN_PLACE_CODE_NAME,
					T9.RSVN_PLACE_CODE_ENG_NAME,
					T9.RSVN_PLACE_CODE_OTH_NAME,
					T1.ROOM_CNT,
					T4.OOO_ROOM_CNT,
					T10.ALLOTMENT,
                    T3.ALLOTMENT,
					T1.SORT_ORDER
				ORDER BY T2.SALE_DATE, T1.SORT_ORDER
				) M
			GROUP BY
				M.ROOM_TYPE_CODE,
				M.ROOM_TYPE_NAME,
				M.RSVN_PLACE_CODE,
				M.RSVN_PLACE_CODE_NAME,
				M.ROOM_CNT,
				M.BSNS_CODE,
				M.PROPERTY_NO,
				M.SORT_ORDER
			ORDER BY M.SORT_ORDER
			) AAA
		WHERE AAA.BSNS_CODE = #BSNS_CODE#
		AND AAA.PROPERTY_NO = #PROPERTY_NO#
	</select>